# Generated by Django 3.2.9 on 2021-12-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_company_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_img',
            field=models.ImageField(default='/home/nicu/Desktop/PoliHackv12/polihack/public/cityImg/pizza.jpg', upload_to='images/cities/'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_img',
            field=models.ImageField(default='/home/nicu/Desktop/PoliHackv12/polihack/public/cityImg/pizza.jpg', upload_to='images/companies'),
        ),
    ]
